services:
  postgres:
    image: pgvector/pgvector:pg17

    container_name: hobbyfi-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: hobbyfi
      POSTGRES_PASSWORD: hobbyfi123
      POSTGRES_DB: hobbyfi

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: